import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Suspense } from "react";
import NavLinks from "@/components/NavLinks";
import Marquee from "@/components/Marquee";
import Hero from "@/components/Hero";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Bazar Dor",
  description: "Generated by create next app",
  icons: "/logo-icon.png",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <Header />

        <Suspense fallback={null}>
          <NavLinks />
        </Suspense>
       <Suspense fallback={<div className="h-8 w-full" />}>
          <Marquee />
        </Suspense>

        <div className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <Hero/>
          {children}
          
        </div>
      </body>
    </html>
  );
}
